apiVersion: datadoghq.com/v1alpha1
kind: WatermarkPodAutoscaler
metadata:
  name: frontend-wpa-hits
  namespace: ecommerce
spec:
  downscaleForbiddenWindowSeconds: 60
  upscaleForbiddenWindowSeconds: 30
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: frontend
  metrics:
  - external:
      highWatermark: "3"
      lowWatermark: "1"
      metricName: "trace.rack.request.hits"
      metricSelector:
        matchLabels:
          service: store-frontend
    type: External
  tolerance: "0.01"